# Generated by Django 3.1.3 on 2021-03-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_auto_20210305_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
