# Generated by Django 3.1.3 on 2021-03-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_auto_20210305_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
